plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 30
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "شعر خانه"
email: mhkaram97@gmail.com
description: "شعر خانه"
github:
  username: mhkarami97
# swiftype:
#   searchId: iXZyPokVfxFaBTvi64Y6
# gitment:
#     repo: blog
#     client_id: a6fb73b3e790e234bab8
#     client_secret: cc10aaff53a03d05ab2ee002dbf401dd7627c7a3

url: "https://poem.mhkarami97.ir"
imgrepo: "https://poem.mhkarami97.ir/static/img"

